### ISSUE TITLE
Need create 1.12.x branch

### ISSUE THREAD

**Issue by tao12345666333** [docker/golang-cross#40]
Go 1.13 is a major release of Go.

And we should create 1.12.x branch. (I don't have push access, can't PR for create a new branch like this https://github.com/tao12345666333/golang-cross/tree/1.12.x)

@thaJeztah PTAL. Thanks.

**Comment by thaJeztah** [comment]
Thanks! I just created a 1.12.x branch; https://github.com/docker/golang-cross/tree/1.12.x

(We can probably remove the 1.10.x branch now that that version has become obsolete)
